
/**
 *
 * @author ruzteo
 */
//This JFrame is the heart of this software, all the UI and interactive elements are handled here.

import com.github.kwhat.jnativehook.GlobalScreen;
import com.github.kwhat.jnativehook.NativeHookException;
import java.awt.AWTException;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
public class frmClicker extends javax.swing.JFrame {
    public boolean human = false;
    Clicker clicker;
    public Listener listener;
    public String strCps = "10";
    public static volatile boolean waitingForKey = false;
    Thread thread;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmClicker.class.getName());

    /**
     * Creates new form frmClicker
     * @throws java.awt.AWTException
     * @throws com.github.kwhat.jnativehook.NativeHookException
     */
    public frmClicker() throws AWTException, NativeHookException {
        
        initComponents();
        clicker = new Clicker();
        listener = new Listener(this);
        ClickerThread clickerThread = new ClickerThread(listener, this, clicker);
        strCps = txtCps.getText();
        lblMode.setText("Mode: Super");
        btnChangeBind.requestFocusInWindow();
        GlobalScreen.registerNativeHook();
        GlobalScreen.addNativeKeyListener(listener);
        GlobalScreen.addNativeMouseListener(listener);
        txtCps.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateCps();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateCps();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
               updateCps();
            }
            private void updateCps(){
                try{
                   int cps = Integer.parseInt(txtCps.getText());
                    clickerThread.setCps(cps);
                    System.out.println("new cps: " + cps); 
                }
                catch(NumberFormatException ignored){
                    
                }
            } 
        }); 
        
        thread = new Thread(clickerThread);
        SwingUtilities.invokeLater(() -> thread.start());

        
        
    }
    public void setStatusText(String text){
        lblkeyBindsName.setText(text);
    }
    public boolean getHuman(boolean human){
        return human;
    }
    public int getCps(int cps){
        return cps;
    }
    public String getStringCps(){
    return txtCps.getText();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChangeBind = new javax.swing.JButton();
        txtCps = new javax.swing.JTextField();
        lblSuper = new javax.swing.JLabel();
        btnHumanActivate = new javax.swing.JButton();
        btnSuperActivate = new javax.swing.JButton();
        lblHuman = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMode = new javax.swing.JLabel();
        lblkeyBindsName = new javax.swing.JLabel();
        lblkeyBinds1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AutoClicker");
        setResizable(false);

        btnChangeBind.setText("Change");
        btnChangeBind.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnChangeBind.setFocusPainted(false);
        btnChangeBind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeBindActionPerformed(evt);
            }
        });

        txtCps.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtCps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCps.setText("10");
        txtCps.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblSuper.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSuper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSuper.setText("Super");

        btnHumanActivate.setText("Activate");
        btnHumanActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHumanActivateActionPerformed(evt);
            }
        });

        btnSuperActivate.setText("Activate");
        btnSuperActivate.setFocusable(false);
        btnSuperActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuperActivateActionPerformed(evt);
            }
        });

        lblHuman.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHuman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHuman.setText("Human");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CPS: ");

        lblMode.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblkeyBindsName.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblkeyBindsName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblkeyBindsName.setText("F");

        lblkeyBinds1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblkeyBinds1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblkeyBinds1.setText("KeyBinds:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMode, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHuman, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSuper, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSuperActivate)
                            .addComponent(btnHumanActivate)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCps, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChangeBind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblkeyBindsName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblkeyBinds1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblkeyBinds1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHuman, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHumanActivate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblkeyBindsName, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSuperActivate, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSuper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChangeBind, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCps, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblMode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        lblkeyBindsName.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHumanActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHumanActivateActionPerformed
        human = true; 
        lblMode.setText("Mode: Human");
    }//GEN-LAST:event_btnHumanActivateActionPerformed

    private void btnSuperActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuperActivateActionPerformed
        human = false;
        lblMode.setText("Mode: Super");
    }//GEN-LAST:event_btnSuperActivateActionPerformed

    private void btnChangeBindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeBindActionPerformed
        //ready to change keybind
        waitingForKey = true; 
        
        
    }//GEN-LAST:event_btnChangeBindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                try {
                    new frmClicker().setVisible(true);
                } catch (NativeHookException ex) {
                    System.getLogger(frmClicker.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
            } catch (AWTException ex) {
                System.getLogger(frmClicker.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeBind;
    private javax.swing.JButton btnHumanActivate;
    private javax.swing.JButton btnSuperActivate;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblHuman;
    private javax.swing.JLabel lblMode;
    private javax.swing.JLabel lblSuper;
    private javax.swing.JLabel lblkeyBinds1;
    private javax.swing.JLabel lblkeyBindsName;
    private javax.swing.JTextField txtCps;
    // End of variables declaration//GEN-END:variables
}
